### ISSUE TITLE
Add GitHub social preview 1280×640px

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-with-mollie-for-gravity-forms#1]
For https://github.com/pronamic/wp-pronamic-pay we have the following image:
https://repository-images.githubusercontent.com/5261169/5758c496-b269-418b-8b7a-1c3ae29af98c

We need one for this plugin as wel in the `1280×640px` format:
https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-gravity-forms/settings

> Upload an image to customize your repository’s social media preview.
>
> Images should be at least 640×320px (1280×640px for best display).

**Comment by kjtolsma** [comment]
![github-mollie-gravity-forms](https://user-images.githubusercontent.com/1701552/222727326-3c36fe90-940c-4efd-a4d3-83b772256ae4.png)
