### ISSUE TITLE
Database error: Cannot add or update a child row: a foreign key constraint fails (`sql_avinart_cli_`.`wp_pronamic_pay_mollie_customer_users`, CONSTRAINT `fk_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `wp_pronamic_pay_mollie_customers` (`id`)).

### ISSUE THREAD

**Issue by soerenmuenster** [pronamic/wp-pronamic-pay-with-mollie-for-gravity-forms#5]
Wordpress Version: 6.5.2
Gravity Forms Version: 2.8.8
Pronamic Pay with Mollie for Gravity Forms Version: 1.4.1 

When you want to test payment oder use it in the form i am getting this error:
Database error: Cannot add or update a child row: a foreign key constraint fails (`sql_avinart_cli_`.`wp_pronamic_pay_mollie_customer_users`, CONSTRAINT `fk_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `wp_pronamic_pay_mollie_customers` (`id`)).

**Comment by remcotolsma** [comment]
This should be fixed in https://github.com/pronamic/wp-pronamic-pay-with-mollie-for-gravity-forms/releases/tag/v1.4.2 → https://wordpress.org/plugins/pronamic-pay-with-mollie-for-gravity-forms/.
